# UAV CTI Lab — Ansible Inventory
# All hosts in the isolated 192.168.100.0/24 research network

[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=.vagrant/machines/default/libvirt/private_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3

[gcs]
gcs-linux    ansible_host=192.168.100.11

[monitoring]
ids-monitor  ansible_host=192.168.100.30

[siem]
siem         ansible_host=192.168.100.40

[cti]
cti-platform ansible_host=192.168.100.50

[uav]
uav-sim      ansible_host=192.168.100.60

[sandbox]
sandbox      ansible_host=192.168.200.70

[lab:children]
gcs
monitoring
siem
cti
uav
